// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjEhifIKkKxviyw9esg9Mki8AXu_6J8H0',
    appId: '1:1009775766965:web:230ef28697bded560cfdfc',
    messagingSenderId: '1009775766965',
    projectId: 'dayvity-ff510',
    authDomain: 'dayvity-ff510.firebaseapp.com',
    storageBucket: 'dayvity-ff510.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArOrS5T8dN5WkSiHTneihmas3qa5PJFMU',
    appId: '1:1009775766965:android:25b3fc72792dcdde0cfdfc',
    messagingSenderId: '1009775766965',
    projectId: 'dayvity-ff510',
    storageBucket: 'dayvity-ff510.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBnnRItaI048mIdkd1xloAh2ZRQxnfWas',
    appId: '1:1009775766965:ios:0d0515be00d937340cfdfc',
    messagingSenderId: '1009775766965',
    projectId: 'dayvity-ff510',
    storageBucket: 'dayvity-ff510.firebasestorage.app',
    iosBundleId: 'com.example.dayvity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBnnRItaI048mIdkd1xloAh2ZRQxnfWas',
    appId: '1:1009775766965:ios:0d0515be00d937340cfdfc',
    messagingSenderId: '1009775766965',
    projectId: 'dayvity-ff510',
    storageBucket: 'dayvity-ff510.firebasestorage.app',
    iosBundleId: 'com.example.dayvity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjEhifIKkKxviyw9esg9Mki8AXu_6J8H0',
    appId: '1:1009775766965:web:7f199fc7f22f83630cfdfc',
    messagingSenderId: '1009775766965',
    projectId: 'dayvity-ff510',
    authDomain: 'dayvity-ff510.firebaseapp.com',
    storageBucket: 'dayvity-ff510.firebasestorage.app',
  );
}
